language: node_js
node_js: 
  - 10

services:
  - docker
before_script:
  - docker pull selenium/standalone-chrome:latest
  - docker container run -d -p 4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:latest
  - docker container ls


addons:
  chrome: stable