language: node_js
node_js: 
  - 10

services:
  - docker
before_script:
  - docker pull selenium/standalone-chrome:latest
  - docker container run -d -p 127.0.0.1:4444:4444 -v /dev/shm:/dev/shm selenium/standalone-chrome:latest
  - sleep 10
  - docker container ls
  


addons:
  chrome: stable