language: node_js
node_js: 
  - 10

services:
  - docker

before_install:
  - docker -v
  - docker-compose -v

install:
  - docker-compose build

before_script:
  - docker-compose up -d
  - sleep 10

script:
  - docker-compose run web-driver ./ci-cd.sh

after_script:
  - docker-compose down